#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : proc-macro2
Version  : 0.4.20
Release  : 12
URL      : https://github.com/alexcrichton/proc-macro2/archive/0.4.20.tar.gz
Source0  : https://github.com/alexcrichton/proc-macro2/archive/0.4.20.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0 MIT
Requires: proc-macro2-data = %{version}-%{release}
Requires: unicode-xid
BuildRequires : cargo
BuildRequires : rustc
BuildRequires : unicode-xid

%description
# proc-macro2
[![Build Status](https://api.travis-ci.org/alexcrichton/proc-macro2.svg?branch=master)](https://travis-ci.org/alexcrichton/proc-macro2)
[![Latest Version](https://img.shields.io/crates/v/proc-macro2.svg)](https://crates.io/crates/proc-macro2)
[![Rust Documentation](https://img.shields.io/badge/api-rustdoc-blue.svg)](https://docs.rs/proc-macro2)

%package data
Summary: data components for the proc-macro2 package.
Group: Data

%description data
data components for the proc-macro2 package.


%prep
%setup -q -n proc-macro2-0.4.20

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
mkdir .cargo
echo "[source.crates-io]
replace-with = 'vendored-sources'
[source.vendored-sources]
directory = '/usr/share/rust/src'" > .cargo/config
echo '{"files":{},"package":""}' > .cargo-checksum.json
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
cargo build --release

%install
cargo clean
install -d -p %{buildroot}/usr/share/rust/src/proc-macro2
cp -a . %{buildroot}/usr/share/rust/src/proc-macro2

%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/rust/src/proc-macro2/.cargo-checksum.json
/usr/share/rust/src/proc-macro2/.cargo/config
/usr/share/rust/src/proc-macro2/.gitignore
/usr/share/rust/src/proc-macro2/.travis.yml
/usr/share/rust/src/proc-macro2/Cargo.lock
/usr/share/rust/src/proc-macro2/Cargo.toml
/usr/share/rust/src/proc-macro2/LICENSE-APACHE
/usr/share/rust/src/proc-macro2/LICENSE-MIT
/usr/share/rust/src/proc-macro2/README.md
/usr/share/rust/src/proc-macro2/build.rs
/usr/share/rust/src/proc-macro2/src/lib.rs
/usr/share/rust/src/proc-macro2/src/stable.rs
/usr/share/rust/src/proc-macro2/src/strnom.rs
/usr/share/rust/src/proc-macro2/src/unstable.rs
/usr/share/rust/src/proc-macro2/tests/test.rs
